name: Project Setup

on:
  workflow_call:
    outputs:
      branch_name:
        description: "Name of the active branch"
        value: ${{ jobs.setup.outputs.branch_name}}
      repo_slug:
        description: "Name of the project repository"
        value: ${{ jobs.setup.outputs.repo_slug}}
      cache-hit:
        description: "If the cache was hit; standard one"
        value: ${{ jobs.setup.outputs.cache-hit}}
      # we can't use the cache_dir from shared workflow since it runs @ own container
      # so instead we upload is as `uv-cache` artifact

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set_branch.outputs.branch_name }}
      repo_slug: ${{ steps.set_repo_slug.outputs.slug }}
      cache-hit: ${{ steps.setup-uv.outputs.cache-hit }}

    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v4

      - name: Determine Branch
        id: set_branch
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Set Repository Slug
        id: set_repo_slug
        run: echo "slug=$(echo ${GITHUB_REPOSITORY#*/})" >> $GITHUB_OUTPUT

      # https://docs.astral.sh/uv/guides/integration/github/#caching
      # https://github.com/astral-sh/setup-uv
      - name: Install UV & Enable caching
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set UV cache dir
        id: set_cache_dir
        run: echo "cache_dir=$UV_CACHE_DIR" >> $GITHUB_OUTPUT

      # https://github.com/actions/setup-python
      # 📝 caching will be managed by UV itself automatically
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Upload cache dir as artifact
        if: ${{ steps.set_cache_dir.outputs.cache_dir != '' }}
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: uv-cache
          path: ${{ steps.set_cache_dir.outputs.cache_dir }}

